default: &default
  sender: gramapi
  host: zephir.gorgu.net
  port: 5672
  vhost: dev-rat
  queue_name: logs
  deferred_time: 5000
  max_attempts: 10
  exchange_name: "agoram_event_exchange"
  user: ratatosk
  password: uG9mL1OmmUxx
  logging_key: "log"


development:
  <<: *default

test:
  <<: *default
  deferred_time: 10
  max_attempts: 2

production:
  <<: *default